### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by aroundthecode**
Hi there
I like your project, but I'll probably need it in both Java API and Maven so I tried to refactor it a bit, here is what I did:
- Refactor code: move all logic in some Managers classes to be used as Java API, now ant task are just mere invokers of such classes. Also tried to add some abstraction form Oracle since I'll need mysql as well.
- Code change: ad urlEncode/Decode function to string to avoid csv token inside row data, change the you you detect cell data from parsing value to table metadata
- Project structure: split project in submodules, one for java API, one to invoke tasks from maven antrun for testing, a third one will be added to manage maven plugin generation.

Hope you will appreciate, more change in next days since I need a bit more "robust" database type management.

### CODE REVIEW

**Comment by mpzarde** [comment]
Hey, can you confirm, any code changes or just moving things around? Also, is it necessary to have a separate jar module or could it be done by having a single module with varying code folders and packages? Fundamentally I don't have any issues and I can merge your changes, just want to have a quick discussion.

**Comment by aroundthecode** [comment]
Some minor code changes, I changed field detection from reading data in the csv which may be erroneous to reading column metadata and therefore changed preparestatement maniging fields.
I created 2 sepratared submodules for 2 reason
1) test submodule has a dependencies on the jar artifact so it has to be build first
2) I will add a third module for a maven plugin shortly and I want to keep API/Ant/maven logically separated.

if you want a easer overview you can see my repository fork.
I will have to add also some more code to provide an option to dump a whole database and not just a single table.
If you are interested I can pull this back as well as soon as it's ready.

**Comment by mpzarde** [comment]
Separate test module? Why not just have test folder under src/test as per maven standard?

**Comment by aroundthecode** [comment]
the puropose of the test module is not to unit-test code but to invoke ant task with taskdef through the maven ant-run plugin. 
It's on a separate module since it need jar dependencies to have taskdef work properly.

**Pull request merged**
